### PR TITLE
Update patterns from BrowserScope’s uap-core

### PR DESCRIPTION
**Pull request by nathany**
From https://github.com/ua-parser/uap-core

### CODE REVIEW

**Comment by idyll** [comment]
Hey @doomspork anything I can do to help out here and get this PR merged?

**Comment by doomspork** [comment]
Wow. Thank you for pinging me @idyll I swore I'd merged this already when I originally reacted to the PR.

**Comment by doomspork** [comment]
@idyll / @nathany I've released 1.6, sorry about that.

**Comment by nathany** [comment]
Thanks Sean

**Comment by doomspork** [comment]
Thank you for the PR @nathany, sorry about for the delay.

If either you or @idyll are interested, I'd be happy to add collaborators to this project.

**Comment by idyll** [comment]
If you don't mind. :) We can set aside time each month to keep the user agents up to date or review PRs or the likes. Just let us know how we can help.

**Pull request merged**
